#if !canImport(ObjectiveC)
import XCTest

extension PathTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PathTests = [
        ("testBasename", testBasename),
        ("testBundleExtensions", testBundleExtensions),
        ("testCodable", testCodable),
        ("testCommonDirectories", testCommonDirectories),
        ("testConcatenation", testConcatenation),
        ("testCopyInto", testCopyInto),
        ("testCopyTo", testCopyTo),
        ("testCopyToExistingDirectoryFails", testCopyToExistingDirectoryFails),
        ("testDataExtensions", testDataExtensions),
        ("testDelete", testDelete),
        ("testDynamicMember", testDynamicMember),
        ("testEnumeration", testEnumeration),
        ("testEnumerationSkippingHiddenFiles", testEnumerationSkippingHiddenFiles),
        ("testExists", testExists),
        ("testExtension", testExtension),
        ("testFileHandleExtensions", testFileHandleExtensions),
        ("testFileReference", testFileReference),
        ("testFilesystemAttributes", testFilesystemAttributes),
        ("testFindCallingExecuteTwice", testFindCallingExecuteTwice),
        ("testFindDepth0", testFindDepth0),
        ("testFindDepthRange", testFindDepthRange),
        ("testFindExecute", testFindExecute),
        ("testFindExtension", testFindExtension),
        ("testFindHidden", testFindHidden),
        ("testFindMaxDepth1", testFindMaxDepth1),
        ("testFindMaxDepth2", testFindMaxDepth2),
        ("testFindMinDepth", testFindMinDepth),
        ("testFindOnNonexistentDirectoryHasNoContent", testFindOnNonexistentDirectoryHasNoContent),
        ("testFindTypes", testFindTypes),
        ("testFlatMap", testFlatMap),
        ("testInitializerForRelativePath", testInitializerForRelativePath),
        ("testIsDirectory", testIsDirectory),
        ("testJoin", testJoin),
        ("testKind", testKind),
        ("testLock", testLock),
        ("testLsOnNonexistentDirectoryReturnsEmptyArray", testLsOnNonexistentDirectoryReturnsEmptyArray),
        ("testMkpathIfExists", testMkpathIfExists),
        ("testMktemp", testMktemp),
        ("testMoveInto", testMoveInto),
        ("testMoveTo", testMoveTo),
        ("testNewStuff", testNewStuff),
        ("testNoUndesiredSymlinkResolution", testNoUndesiredSymlinkResolution),
        ("testOptionalInitializer", testOptionalInitializer),
        ("testParent", testParent),
        ("testPathComponents", testPathComponents),
        ("testReadlinkOnFileReturnsSelf", testReadlinkOnFileReturnsSelf),
        ("testReadlinkOnNonExistantFileThrows", testReadlinkOnNonExistantFileThrows),
        ("testReadlinkOnRelativeSymlink", testReadlinkOnRelativeSymlink),
        ("testReadlinkWhereLinkDestinationDoesNotExist", testReadlinkWhereLinkDestinationDoesNotExist),
        ("testRealpath", testRealpath),
        ("testRelativeCodable", testRelativeCodable),
        ("testRelativePathCodable", testRelativePathCodable),
        ("testRelativeTo", testRelativeTo),
        ("testRename", testRename),
        ("testSort", testSort),
        ("testStringConvertibles", testStringConvertibles),
        ("testStringExtensions", testStringExtensions),
        ("testSymlinkFunctions", testSymlinkFunctions),
        ("testTimes", testTimes),
        ("testTouchThrowsIfCannotWrite", testTouchThrowsIfCannotWrite),
        ("testURLInitializer", testURLInitializer),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(PathTests.__allTests__PathTests),
    ]
}
#endif
